### ISSUE TITLE
7TV CDN links missing file extension 

### ISSUE THREAD

**Issue by badoge** [omegastreamtv/YEAHBUTDVDs#16]
The site loads emotes without the file extension which results in a 403 error https://cdn.7tv.app/emote/63071bb9464de28875c52531/3x

CDN links should have a file extension https://cdn.7tv.app/emote/63071bb9464de28875c52531/3x.webp

The API already returns the CDN links so it's better to use those instead of manually creating them using the emote id

**Comment by Mahcks** [comment]
Hey badoge, thanks for letting me know about the issue! I went ahead and patched in a fix and merged it in. Let me know if that fixes it for you. 

Thanks!

**Comment by badoge** [comment]
Fixed 👍
