### ISSUE TITLE
[BUG] My channel doesnt exist

### ISSUE THREAD

**Issue by 7JEO** [omegastreamtv/YEAHBUTDVDs#7]
my channel
![image](https://user-images.githubusercontent.com/79304571/154193698-f5cccb1b-16c5-4f4b-b9c9-9a9df390e2d9.png)

**Comment by acdvs** [comment]
The API is down at the moment. We're working on fixing some internal issues. Apologies for any trouble it's caused!

**Comment by Mahcks** [comment]
Sorry for the inconvenience, the API is back online! 👍
